filas-dinamica: filas-dinamica.o
	./filas-dinamica.o
filas-dinamica.o: filas-dinamica.c
	gcc -o filas-dinamica.o filas-dinamica.c
filas-estatica: filas-estatica.o
	./filas-estatica.o
filas-estatica.o: filas-estatica.c
	gcc -o filas-estatica.o filas-estatica.c
	